#!/bin/sh
set -e

case "$1" in
    configure)
    if ! getent group nastools-netdata >/dev/null 2>&1; then
        rn_nml -a group:nastools-netdata
    fi
    if ! getent passwd nastools-netdata >/dev/null 2>&1; then
        rn_nml -a user:nastools-netdata:nastools-netdata
    fi
    chattr +C /apps/nastools-netdata/var/cache/netdata
    setcap cap_dac_read_search,cap_sys_ptrace+ep /apps/nastools-netdata/lib/*/netdata/plugins.d/apps.plugin
    chown -R nastools-netdata:nastools-netdata /apps/nastools-netdata
    chown root /apps/nastools-netdata/lib/*/netdata/plugins.d/apps.plugin
    chmod 4755 /apps/nastools-netdata/lib/*/netdata/plugins.d/apps.plugin
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
