---
- name: "Install pre-requisites"    
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - gcc
    - git
    - libmnl-dev
    - make
    - pkg-config
    - uuid-dev
    - zlib1g-dev
  when: ansible_os_family == "Debian"

- name: "Install pre-requisites"    
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - curl
    - gcc
    - git
    - jq
    - libmnl-devel
    - libuuid-devel
    - make
    - pkgconfig
    - zlib-devel
  when: ansible_os_family == "RedHat"

- name: "Clone repo"
  git:
    clone: yes
    repo: https://github.com/firehol/netdata.git
    dest: /tmp/netdata

- name: "Installation"
  shell: cd /tmp/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here

- name: "Clean /tmp"
  file:
    path: /tmp/netdata
    state: absent

- name: "KillAll"
  shell: killall netdata

- name: "Daemon config"
  systemd:
    daemon_reload: yes
    name: netdata
    enabled: yes
    state: started
